In [1]:
 # κάνουμε update τις βιβλιοθήκες μας
!pip install -U scikit-learn
!pip install --upgrade pandas
!pip install -U scipy
!pip install --upgrade numpy 

Requirement already up-to-date: scikit-learn in /usr/local/lib/python3.6/dist-packages (0.23.2)
Requirement already up-to-date: pandas in /usr/local/lib/python3.6/dist-packages (1.1.4)
Requirement already up-to-date: scipy in /usr/local/lib/python3.6/dist-packages (1.5.4)
Requirement already up-to-date: numpy in /usr/local/lib/python3.6/dist-packages (1.19.4)


# Αξιολόγηση ταξινόμησης με ακρίβεια, ανάκληση και F1, μέσοι όροι
Η πιστότητα είναι μια πολύ χρήσιμη και πρακτική μετρική της απόδοσης ενός ταξινομητή. Ωστόσο, δεν αρκεί για μια ολοκληρωμένη μελέτη της απόδοσής του. Είναι τυπικό για όλα τα προβλήματα machine learning να χρησιμοποιούμε διαφορετικές μετρικές για να μελετήσουμε τις ιδιότητες των δεδομένων. 

Καταρχάς, ας ξαναφέρουμε το Iris dataset και τον kNN και ας κάνουμε προβλέψεις με τον default kNN (είναι ακριβώς ο κώδικας από το προηγούμενο notebook σε ένα cell)

In [2]:
# Load Iris and organize our data
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix
data = load_iris()
label_names = data['target_names']
labels = data['target']
feature_names = data['feature_names']
features = data['data']
# Χρησιμοποιούμε τη γνωστή train_test_split για να διαχωρίσουμε σε train και test set
# το (int) όρισμα "random_state" είναι το seed της γεννήτριας τυχαίων αριθμών (αν του δώσουμε τιμή θα παράξει την ίδια σειρά τυχαίων αριθμών)
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.40, random_state=78)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
for i in range(1,40):
  knn = KNeighborsClassifier(n_neighbors=i)
  knn.fit(X_train, y_train)
  pred = knn.predict(X_test)
  # Compute confusion matrix
  cnf_matrix = confusion_matrix(y_test, pred)
  # τυπώνουμε τα labels
  print(label_names, "\n")
  # τυπώνουμε το confusion matrix
  print(cnf_matrix)  

['setosa' 'versicolor' 'virginica'] 

[[20  0  0]
 [ 0 21  2]
 [ 0  0 17]]
['setosa' 'versicolor' 'virginica'] 

[[20  0  0]
 [ 0 21  2]
 [ 0  0 17]]
['setosa' 'versicolor' 'virginica'] 

[[20  0  0]
 [ 0 21  2]
 [ 0  0 17]]
['setosa' 'versicolor' 'virginica'] 

[[20  0  0]
 [ 0 22  1]
 [ 0  0 17]]
['setosa' 'versicolor' 'virginica'] 

[[20  0  0]
 [ 0 22  1]
 [ 0  0 17]]
['setosa' 'versicolor' 'virginica'] 

[[20  0  0]
 [ 0 22  1]
 [ 0  0 17]]
['setosa' 'versicolor' 'virginica'] 

[[20  0  0]
 [ 0 21  2]
 [ 0  0 17]]
['setosa' 'versicolor' 'virginica'] 

[[20  0  0]
 [ 0 21  2]
 [ 0  0 17]]
['setosa' 'versicolor' 'virginica'] 

[[20  0  0]
 [ 0 21  2]
 [ 0  0 17]]
['setosa' 'versicolor' 'virginica'] 

[[20  0  0]
 [ 0 22  1]
 [ 0  0 17]]
['setosa' 'versicolor' 'virginica'] 

[[20  0  0]
 [ 0 21  2]
 [ 0  0 17]]
['setosa' 'versicolor' 'virginica'] 

[[20  0  0]
 [ 0 21  2]
 [ 0  0 17]]
['setosa' 'versicolor' 'virginica'] 

[[20  0  0]
 [ 0 21  2]
 [ 0  0 17]]
['setosa' 'versicolor' 'v

Η βάση για τις μετρικές απόδοσης των ταξινομητών είναι ο πίνακας σύγχυσης (confusion matrix). O πίνακας σύχγυσης $C$  είναι τέτοιος ώστε το $C_{i, j}$ είναι ίσο με τα δείγματα που ενώ ανήκουν στην κατηγορία $i$ ταξινομήθηκαν στην κατηγορία  $j$. Για το Iris, στο συγκεκριμένο train/test split, o πίνακας σύγχυσης είναι:

In [3]:
from sklearn.metrics import confusion_matrix
# Compute confusion matrix
cnf_matrix = confusion_matrix(y_test, pred)
# τυπώνουμε τα labels
print(label_names, "\n")
# τυπώνουμε το confusion matrix
print(cnf_matrix)

['setosa' 'versicolor' 'virginica'] 

[[20  0  0]
 [ 0 20  3]
 [ 0  0 17]]


που σημαίνει ότι 1 δείγμα που άνηκε κανονικά στο είδος versicolor ταξινομήθηκε λανθασμένα στο είδος virginica. Τα στοιχεία της διαγωνίου είναι αληθινά θετικά δείγματα (true positive) της κάθε κλάσης. Για κάθε κλάση $i$ τα στοιχεία της γραμμής $i$ εκτός της διαγωνίου είναι λάνθασμένα αρνητικά δείγματα (false negative) της κλάσης και τα στοιχεία της κολώνας $i$ εκτός της διαγωνίου είναι λανθασμένα θετικά δείγματα (false positive) της κλάσης. 


<figure>
  <center>
  <img src="http://scikit-learn.org/stable/_images/sphx_glr_plot_confusion_matrix_001.png" alt="Confusion Matrix">
   <figcaption>Confusion matrix στο Iris - αλλος ταξινομητής (SVM)</figcaption>
  </center>
</figure>


Σε περίπτωση δυαδικού ταξινομητή $C_{0,0}$ είναι τα αληθινά αρνητικά δείγματα (true negative, η κλάση 0 θεωρείται η αρνητική), $C_{1,0}$ είναι τα λανθασμένα αρνητικά δείγματα, $C_{1,1}$ τα αληθινά θετικά δείγματα και $C_{0,1}$ τα λανθασμένα θετικά. Για παράδειγμα:

In [4]:
# παράδειγμα confusion matrix σε δυαδική ταξινόμηση
tn, fp, fn, tp = confusion_matrix([0, 1, 0, 1], [1, 1, 1, 0]).ravel()
print(tn, fp, fn, tp)

0 2 1 1


Συχνά στην δυαδική ταξινόμηση θεωρούμε θετική την πιο σπάνια κλάση ή το φαινόμενο προς εντοπισμό (πχ διαβητικός). 

![CMMulti2](https://drive.google.com/uc?id=143alsFB2Xbjovf2kCcErg2FKf6XFLyn-)

![CMMulti21](https://drive.google.com/uc?id=1Oqen4t9o_IBGHXzWjN9s_RcS3MAfJZuP)
Ορίζουμε:
Ακρίβεια -Precision- ($P$) είναι ο λόγος των true positives ($T_p$) ως προς τον αριθμό των true positives συν τον αριθμό των false positives ($F_p$).
$$P = \frac{T_p}{T_p+F_p}$$
Ανάκληση -Recall- ($R$) είναι ο λόγος των true positives ($T_p$) ως προς τον αριθμό των true positives συν τον αριθμό των false negatives ($F_n$).
$$R = \frac{T_p}{T_p + F_n}$$
Συχνά χρησιμοποιούμε και το ($F_1$) score, το οποίο είναι ο αρμονικός μέσος της ακρίβειας και της ανάκλησης.
$$F1 = 2\frac{P \times R}{P+R}$$
Ιδανικά θέλουμε και υψηλή ακρίβεια και υψηλή ανάκληση, ωστόσο μεταξύ της ακρίβειας και της ανάκλησης υπάρχει γενικά trade-off. Στην οριακή περίπτωση του ταξινομητή που επιστρέφει σταθερά μόνο τη θετική κλάση για παράδειγμα, η ανάκληση θα είναι 1 αλλά η ακρίβεια θα έχει τη μικρότερη δυνατή τιμή της. Γενικά, κατεβάζοντας το κατώφλι της απόφασης του ταξινομητή, αυξάνουμε την ανάκληση και μειώνουμε την ακρίβεια και αντιστρόφως.

Στην πράξη και ειδικά σε μη ισορροπημένα datasets χρησιμοποιούμε την ακρίβεια, ανάκληση και το F1 πιο συχνά από την πιστότητα. Επίσης, ανάλογα την εφαρμογή μπορεί να μας ενδιαφέρει περισσότερο ένα συγκεκριμένο metric, πχ η ανάκληση (πχ στη διάγνωση μιας ασθένειας) ή η ακρίβεια (πχ σε μια οικονομική απόφαση).

In [5]:

from sklearn.metrics import precision_recall_fscore_support

# εκτυπώνουμε 4 πίνακες, precision, recall, F1 και support. Support είναι ο συνολικός αριθμός προβλέψεων σε κάθε κλάση
# το πρώτο στοιχείο του κάθε πίνακα είναι η κλάση setosa, το δεύτερο η versicolor και το τρίτο η virginica
print(precision_recall_fscore_support(y_test, pred, average=None), "\n")

# εκτυπώνουμε τa precision, recall και F1 λαμβάνοντας υπόψη συνολικά (αθροίζοντας εκτός κλάσεων) τα δείγματα (average = micro).
print(precision_recall_fscore_support(y_test, pred, average='micro'), "\n")

# εκτυπώνουμε το μέσο όρο των precision, recall και F1 θεωρώντας ότι οι κλάσεις έχουν το ίδιο βάρος (average = macro)
print(precision_recall_fscore_support(y_test, pred, average='macro'), "\n")

# εκτυπώνουμε τa precision, recall και F1 λαμβάνοντας. Με average = weighted κάθε κλάση μετρά στο μέσο όρο ανάλογα με το support της.
print(precision_recall_fscore_support(y_test, pred, average='weighted'), "\n")

# η classification_report τυπώνει πιο ωραία οπτικά σε string τα αποτελέσματα
# πρώτα για κάθε κλάση και μετά με μέσους όρους
print("a")
from sklearn.metrics import classification_report
print(classification_report(y_test, pred, target_names=label_names))

(array([1.  , 1.  , 0.85]), array([1.        , 0.86956522, 1.        ]), array([1.        , 0.93023256, 0.91891892]), array([20, 23, 17])) 

(0.95, 0.95, 0.9500000000000001, None) 

(0.9500000000000001, 0.9565217391304347, 0.9497171590194845, None) 

(0.9575, 0.95, 0.9502828409805153, None) 

a
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        20
  versicolor       1.00      0.87      0.93        23
   virginica       0.85      1.00      0.92        17

    accuracy                           0.95        60
   macro avg       0.95      0.96      0.95        60
weighted avg       0.96      0.95      0.95        60



Documentation από το scikit σχετικά με την αξιολόγηση των μοντέλων:

* [sklearn.metrics.precision_recall_fscore_support](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_recall_fscore_support.html)
* [Model evaluation: quantifying the quality of predictions](http://scikit-learn.org/stable/modules/model_evaluation.html#multiclass-and-multilabel-classification)
* [Multiclass and multilabel classification](http://scikit-learn.org/stable/modules/model_evaluation.html#multiclass-and-multilabel-classification)

Σημειώστε ότι όταν η classification report μέχρι το version 0.19 του scikit τυπώνει μόνο ένα μέσο όρο, τον weighted. (σχετική συζήτηση [εδώ](https://stackoverflow.com/questions/23914472/strange-f1-score-result-using-scikit-learn)).

# Άσκηση: Σύγκριση του Gausian Naive Bayes και του kNN στo Pima Indians Diabetes dataset
![1889 Photograph shows half-length portrait of two Pima Indians, facing front, wearing bead necklaces.](https://i.pinimg.com/236x/60/05/76/600576905d4ad5bb1a9c3e3387b397ca--pima-indians-native-american-indians.jpg "1889 Photograph shows half-length portrait of two Pima Indians, facing front, wearing bead necklaces.")

Διαβάστε το ["pima-indians-diabetes.data.csv"](https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv) σε ένα numpy array data και ξεχωρίστε features και labels.

Για 40% test set: 
1. υπολογίστε την πρόβλεψη του Gaussian Naive Bayes με τη μέθοδο predict(). 
2. πάρτε τις προβλέψεις ενός kNN με k=5
3. Για έναν ταξινομητή kNN, με 3-fold cross validation και με μετρική 'f1_weighted' υπολογίστε το βέλτιστο k στο train set (maximum k=50). 
4. εκτυπώστε με την "classification_report" τα precision, recall, f1, support για τον NB, τον kNN με k=5 και με το k που έχει προκύψει από cross validation.
5. Κάντε 3 runs και αποθηκεύστε σε ένα κελί markdown το average F1 του non optimized και του optimized kNN. Πόσο % έχει βελτιβωθεί η επίδοσή του; 

hint: Για τη δημιουργία πινάκων σε markdown μπορείτε να χρησιμοποιείτε ένα [markdown table generator](https://www.tablesgenerator.com/markdown_tables)

In [ ]:
import pandas as pd
df = pd.read_csv("pima-indians-diabetes.data.csv", header=None)
df

0    1   2   3    4     5      6   7  8
0     6  148  72  35    0  33.6  0.627  50  1
1     1   85  66  29    0  26.6  0.351  31  0
2     8  183  64   0    0  23.3  0.672  32  1
3     1   89  66  23   94  28.1  0.167  21  0
4     0  137  40  35  168  43.1  2.288  33  1
..   ..  ...  ..  ..  ...   ...    ...  .. ..
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

[768 rows x 9 columns]

In [ ]:
labels_df = df.iloc[:, [8]] # τα labels είναι στη δεύτερη κολώνα
features_df = df.iloc[:, 0:8]

In [ ]:
import numpy as np
features = features_df.values
labels = labels_df.values.reshape(768,)
print(labels.shape)

(768,)


In [ ]:
labels.astype(int)
print ("frequencies:", np.bincount(labels))


frequencies: [500 268]


In [ ]:
print("f1 {}, f2 {}".format(np.bincount(labels)[0]/labels.shape, "bf"))

f1 [0.65104167], f2 bf


In [ ]:
from sklearn.model_selection import train_test_split

# Split our data
train, test, train_labels, test_labels = train_test_split(features, labels, test_size=0.4)

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
# κάνουμε εκπαίδευση (fit) δηλαδή ουσιαστικά υπολογίζουμε μέση τιμή και διακύμανση για όλα τα χαρακτηριστικά και κλάσεις στο training set
model = gnb.fit(train, train_labels)
# η GaussianNB έχει builtin μέθοδο υπολογισμό accuracy. Αποθηκεύουμε την τιμή της στον πίνακά μας με τα αποτελέσματα από τα άλλα classifiers
pred_gnb = model.predict(test)

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
model = knn.fit(train,train_labels)
pred_knn5 = model.predict(test)

In [ ]:
# φτιάχνουμε μια λίστα από το 1 έως το 50
myList = list(range(1,50))
# Κρατάμε μόνο τα περιττά k
neighbors = list(filter(lambda x: x % 2 != 0, myList))

# perform 3-fold cross validation
max = -1
max_k = -1
for k in neighbors:
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn, train, train_labels, cv=3, scoring='f1_weighted')
    max, max_k = (scores.mean(), k) if scores.mean() > max  else (max, max_k)
knn_opt = KNeighborsClassifier(n_neighbors=max_k)
model = knn_opt.fit(train,train_labels)
pred_knn_opt = model.predict(test)

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(test_labels, pred_gnb))
print(classification_report(test_labels, pred_knn5))
print(classification_report(test_labels, pred_knn_opt))


              precision    recall  f1-score   support

           0       0.83      0.80      0.82       209
           1       0.61      0.65      0.63        99

    accuracy                           0.75       308
   macro avg       0.72      0.73      0.72       308
weighted avg       0.76      0.75      0.76       308

              precision    recall  f1-score   support

           0       0.80      0.80      0.80       209
           1       0.58      0.58      0.58        99

    accuracy                           0.73       308
   macro avg       0.69      0.69      0.69       308
weighted avg       0.73      0.73      0.73       308

              precision    recall  f1-score   support

           0       0.81      0.81      0.81       209
           1       0.60      0.59      0.59        99

    accuracy                           0.74       308
   macro avg       0.70      0.70      0.70       308
weighted avg       0.74      0.74      0.74       308

